// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Gjinchao/Go-000/Week04/api"
	"github.com/Gjinchao/Go-000/Week04/internal/biz"
	"github.com/Gjinchao/Go-000/Week04/internal/data"
	"github.com/Gjinchao/Go-000/Week04/internal/service"
)

// Injectors from wire.go:

func InitializeAllInstance() api.AccountInterface {
	accountRepo := data.NewAccountRepo()
	accountBiz := biz.NewAccountBiz(accountRepo)
	accountService := service.NewAccountService(accountBiz)
	accountInterface := api.NewAccountInterface(accountService)
	return accountInterface
}
